site_name: Alphaus Engineering Blog
theme:
  name: material
  logo: assets/alphaus-logo-line-transparent.png
  favicon: assets/alphaus.png
  features:
  - navigation.sections
plugins:
- meta
- blog:
    blog_dir: .
- search
- tags
nav:
- index.md
copyright: >
  Copyright &copy; 2023 Alphaus, Inc.  
  <a href="#__consent">Change cookie settings</a>
markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- md_in_html
- footnotes
