site_name: Alphaus Engineering Blog
theme:
  name: material
  logo: assets/alphaus-logo-line-transparent.png
  favicon: assets/alphaus.png
  features:
  - navigation.sections
plugins:
- meta
- blog:
    blog_dir: .
- search
- tags
nav:
- index.md
