authors:
  flowerinthenight:
    name: Chew
    description: "CTO, Alphaus"
    avatar: https://gravatar.com/avatar/2de9af8f37952c6e9d9a5f7a145c988a6f266ea03265d56498b1fd1a037844a8
    url: https://flowerinthenight.com/
