flowerinthenight:
  name: Flowerinthenight
  description: CTO, Alphaus, Inc.
  avatar: https://bnz05pap001files.storage.live.com/y4mP7Kzxz8py1CCuuzPta6_c5ZSYU-_DlUqkNyK7Xj9Wmqspz6Q14gy0U0XjnDPFUbSULTqr62KxkgS81PHrmpVJxDnDKu2fU4L7CRffSeKSwUMZin1NCvc4BxIh9dxFgcIiUmzpFALAagShD-p3-yPmpVJo0XXjvSziWjrgT4S3RhPZHcLuOaxHkI-bQWR6Ce1?width=552&height=552&cropmode=none
